jd : [0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001]
ll : [0,   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 0.1, 0, 0, 0, -1.57079632679, -3.53429173529, -0.392699081699, -2.09439510239, -1.57079632679, -2.09439510239, 0, 0]
ul : [0,   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  
    # # torso
    0.3, 0, 0, 2.74889357189, 1.0908307825, 1.57079632679, 2.35619449019, 2.09439510239, 1.57079632679, 2.09439510239, 0, 0]
jr :  [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1.9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
rest_pose : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


environment:
    model: "ISRoboNet_home_testbed.urdf"

# Saywer
robot:
    model: "sawyer_robot/sawyer_description/urdf/sawyer.urdf"
    endeffector_index : 16
    name : "sawyer"
    origin_pos : [0, -0.7, 0.98]
    origin_orientation : [0.000354607015924, 0.000618012458393, 0.722125656896, 0.691761539815]



